# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nick Caley
email: ncc.fkc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal site for cool stuff related to [probably] programming,
  software, and just cool things in general. You should check here some 
  times for new stuff. Maybe I'll even post a few things or doodles.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://spudfkc.github.io" # the base hostname & protocol for your site
twitter_username: spud_
github_username:  spudfkc

# Build settings
markdown: kramdown
